"""Parser regressions: heading paths, front matter, fence repair, chunking, units.

One test per defect found in code review; each fails when its fix is reverted.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from fakes import FakeEmbedder
from helpers import parse, paths

from markdown_memory.db import Database
from markdown_memory.indexer import Indexer
from markdown_memory.models import (
    PREAMBLE_TITLE,
    SectionDraft,
)
from markdown_memory.parser import DEFAULT_MAX_SECTION_CHARS, MarkdownParser, join_parts
from markdown_memory.search import HybridSearcher


class TestUniquePaths:
    def test_generated_suffix_never_collides_with_a_literal_heading(self) -> None:
        document = parse("# Log\n\n## Fixed\n\na\n\n## Fixed [2]\n\nb\n\n## Fixed\n\nc\n")
        assert paths(document) == ["Log", "Log > Fixed", "Log > Fixed [2]", "Log > Fixed [3]"]
        assert len(set(paths(document))) == len(document.sections)

    def test_many_duplicates_with_literal_lookalikes(self) -> None:
        document = parse("# X\n\n# X [3]\n\n# X\n\n# X\n\n# X [2]\n")
        assert len(set(paths(document))) == 5

    def test_real_heading_named_like_a_generated_part(self) -> None:
        body = "\n\n".join(f"Sentence number {n} is here. " * 12 for n in range(12))
        text = f"# Tutorial\n\n{body}\n\n# Tutorial (Part 2)\n\nThe real second chapter.\n"
        document = parse(text)
        found = paths(document)
        assert len(set(found)) == len(found)
        assert "Tutorial (Part 2)" in found  # the generated part keeps the plain name
        real = next(s for s in document.sections if "real second chapter" in s.content)
        assert real.heading_path == "Tutorial (Part 2) [2]"
        assert real.part_index == 0

    def test_literal_part_heading_before_the_oversized_section(self) -> None:
        body = "\n\n".join(f"Sentence number {n} is here. " * 12 for n in range(12))
        document = parse(f"# Guide (Part 1)\n\nliteral\n\n# Guide\n\n{body}\n")
        found = paths(document)
        assert len(set(found)) == len(found)
        assert found[0] == "Guide (Part 1)"
        assert found[1].startswith("Guide [2] (Part ")

    def test_heading_named_like_the_preamble(self) -> None:
        document = parse(f"intro\n\n# {PREAMBLE_TITLE}\n\nbody\n")
        assert paths(document) == [PREAMBLE_TITLE, f"{PREAMBLE_TITLE} [2]"]


class TestHeadingTitles:
    def test_type_parameters_survive_in_titles(self) -> None:
        text = (
            "# Types\n\n## Option<T>\n\na\n\n## Option<U>\n\nb\n\n## The <details> element\n\nc\n"
        )
        assert paths(parse(text)) == [
            "Types",
            "Types > Option<T>",
            "Types > Option<U>",
            "Types > The <details> element",
        ]

    def test_formatting_html_is_still_stripped(self) -> None:
        document = parse('# The <b>bold</b> H<sub>2</sub>O <a href="x">link</a><!-- note -->\n')
        assert paths(document) == ["The bold H2O link"]


class TestFrontMatterDetection:
    def test_leading_thematic_break_is_not_front_matter(self) -> None:
        document = parse("---\n\n# Project\n\nIntro\n\n---\n\n## Usage\n\nrun it\n")
        assert paths(document)[-2:] == ["Project", "Project > Usage"]
        assert document.title == "Project"

    def test_heading_then_ellipsis_is_not_front_matter(self) -> None:
        document = parse("---\n# Project\n\nWait for it\n...\n\n## Usage\n\nrun\n")
        assert "Project > Usage" in paths(document)

    def test_prose_with_a_colon_is_not_front_matter(self) -> None:
        document = parse("---\nNote: read this first\nSome prose follows here\n---\n\n# T\n")
        assert document.title == "T"
        assert not any("Note" in s.content for s in document.sections if s.heading_level == 0)

    def test_real_front_matter_with_lists_comments_and_blocks(self) -> None:
        text = (
            "---\n# generated by a tool\ntitle: 'Real'\ntags:\n  - a\n  - b\n"
            "summary: |\n  multi\n  line\n\nnested:\n  key: value\n---\n\n## Body\n\ntext\n"
        )
        document = parse(text)
        assert document.title == "Real"
        assert paths(document) == [PREAMBLE_TITLE, "Body"]


class TestUnclosedFenceBeforeLaterFences:
    def test_later_info_fence_does_not_hide_the_swallowed_heading(self) -> None:
        text = "# A\n\n```bash\nls\n\n## B\n\nB text\n\n```python\nx = 1\n```\n\n## C\n\nmore\n"
        document = parse(text)
        assert paths(document) == ["A", "A > B", "A > C"]
        assert "```python\nx = 1\n```" in document.sections[1].content

    def test_bare_later_fences_flip_parity_and_everything_is_recovered(self) -> None:
        text = (
            "# A\n\n```bash\nls\n\n## B\n\nB text\n\n```\nx = 1\n```\n\n## C\n\nmore\n\n"
            "```\ny\n```\n\n## D\n\nend\n"
        )
        assert paths(parse(text)) == ["A", "A > B", "A > C", "A > D"]

    def test_longer_outer_fence_with_an_inner_example_is_left_alone(self) -> None:
        text = "# Doc\n\n````md\n\n## Example\n\n```python\nx = 1\n```\n\n````\n\n## Real\n"
        assert paths(parse(text)) == ["Doc", "Doc > Real"]

    def test_tilde_fence_holding_a_backtick_example_is_left_alone(self) -> None:
        text = "# Doc\n\n~~~md\n\n## Example\n\n```python\nx = 1\n```\n\n~~~\n\n## Real\n"
        assert paths(parse(text)) == ["Doc", "Doc > Real"]

    def test_well_formed_fences_with_hash_comments_are_untouched(self) -> None:
        text = (
            "# Doc\n\n```bash\nmake\n\n## build everything\nmake all\n```\n\n## Next\n\n"
            "```yaml\na: 1\n\n## section comment\nb: 2\n```\n\n## Last\n"
        )
        assert paths(parse(text)) == ["Doc", "Doc > Next", "Doc > Last"]

    def test_candidate_that_would_not_repair_the_document_is_rejected(self) -> None:
        # The final bare fence really is unclosed; cutting the earlier, well-formed bash
        # fence at its "## comment" would flip every later marker instead of fixing it.
        text = (
            "# Doc\n\n```bash\nmake\n\n## comment\nmake all\n```\n\n## Middle\n\ntext\n\n"
            "```\nnever closed\n\n## After\n\nend\n"
        )
        assert paths(parse(text)) == ["Doc", "Doc > Middle", "Doc > After"]


class TestFenceSafeChunking:
    def test_fence_that_fits_alone_is_not_cut_because_of_the_heading(self) -> None:
        code = "```python\n" + "\n".join(f"line_{n} = {n}" for n in range(225)) + "\n```"
        assert len(code) <= DEFAULT_MAX_SECTION_CHARS
        text = f"# A heading that is a little longer\n\n{code}\n\nAfter paragraph.\n"
        assert len(text) > DEFAULT_MAX_SECTION_CHARS
        document = parse(text)
        holders = [s for s in document.sections if "line_0 = 0" in s.content]
        assert len(holders) == 1
        assert code in holders[0].content
        assert join_parts(document.sections) == text.rstrip("\n")

    def test_fence_indented_inside_a_list_item_is_kept_whole(self) -> None:
        filler = "\n\n".join("filler paragraph text " * 20 for _ in range(6))
        code = (
            "    ```python\n"
            + "\n\n".join(f"    def function_{n}():\n        return {n}" for n in range(30))
            + "\n    ```"
        )
        text = f"# Guide\n\n{filler}\n\n1. Install:\n\n{code}\n\n{filler}\n"
        # the fence starts before the 3200-character boundary and ends after it
        assert text.index("```python") < DEFAULT_MAX_SECTION_CHARS < text.index("\n    ```\n")
        assert len(code) <= DEFAULT_MAX_SECTION_CHARS
        document = parse(text)
        holders = [s for s in document.sections if "def function_" in s.content]
        assert len(holders) == 1
        assert code in holders[0].content
        assert join_parts(document.sections) == text.rstrip("\n")


SKILL_DOC = """# Skill Authoring

## Writing a Skill

Put this in `SKILL.md`:

```markdown
# My Skill

## Usage

Run the command:

```bash
my-skill run
```

That is all you need.

## Publishing

Push the folder.
"""

STRAY_FENCE_DOC = """# Data Pipeline

## Loading

```python
import pandas as pd

## Load the raw frame

frame = pd.read_csv("in.csv")
```

## Cleaning

Drop the nulls.

## Output

Write it back.

```
"""


class TestFenceRepairNeverDamagesWellFormedDocuments:
    def test_markdown_sample_holding_an_inner_fence_is_left_alone(self) -> None:
        document = parse(SKILL_DOC)
        assert paths(document) == [
            "Skill Authoring",
            "Skill Authoring > Writing a Skill",
            "Skill Authoring > Publishing",
        ]
        assert "```bash\nmy-skill run\n```" in document.sections[1].content

    @pytest.mark.parametrize("language", ["markdown", "md", "text", ""])
    def test_sample_languages_are_exempt_from_the_nested_opener_rule(self, language: str) -> None:
        text = (
            f"# Doc\n\nIntro.\n\n```{language}\n\n## Example\n\nbody\n\n```js\nx()\n```\n\nTail.\n"
        )
        assert paths(parse(text)) == ["Doc"]

    def test_stray_closing_fence_does_not_swallow_real_headings(self) -> None:
        document = parse(STRAY_FENCE_DOC)
        assert paths(document) == [
            "Data Pipeline",
            "Data Pipeline > Loading",
            "Data Pipeline > Cleaning",
            "Data Pipeline > Output",
        ]
        assert "## Load the raw frame" in document.sections[1].content  # still code

    def test_stray_fence_after_a_markdown_sample(self) -> None:
        text = (
            "# Doc\n\n```md\nintro\n\n## Sample\n\nbody\n```\n\n## Real Section\n\nprose\n\n```\n"
        )
        assert paths(parse(text)) == ["Doc", "Doc > Real Section"]

    def test_code_fence_holding_another_languages_opener_is_still_repaired(self) -> None:
        text = "# A\n\n```bash\nls\n\n## B\n\nB text\n\n```python\nx = 1\n```\n\n## C\n\nmore\n"
        assert paths(parse(text)) == ["A", "A > B", "A > C"]


class TestParserScaling:
    def test_each_section_is_built_once_however_many_duplicates(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        body = "\n\n".join("paragraph of filler text " * 12 for _ in range(14))  # oversized
        text = "# Log\n\n" + "".join(f"## Entry\n\n{body}\n\n" for _ in range(60))
        builds = 0
        real = MarkdownParser._build_section

        def counting(self: MarkdownParser, *args: object, **kwargs: object) -> list[SectionDraft]:
            nonlocal builds
            builds += 1
            return real(self, *args, **kwargs)  # type: ignore[arg-type]

        monkeypatch.setattr(MarkdownParser, "_build_section", counting)
        document = parse(text)
        assert builds == 62  # preamble + "Log" + 60 entries; it was 1 + 1 + (1 + 2 + ... + 60)
        found = paths(document)
        assert len(set(found)) == len(found)
        assert "Log > Entry [60] (Part 2)" in found
        entry_60 = [s for s in document.sections if s.base_path == "Log > Entry [60]"]
        assert all(s.heading_title == "Entry [60]" for s in entry_60)
        assert join_parts(entry_60) == f"## Entry\n\n{body}"


class TestFrontMatterKeys:
    @pytest.mark.parametrize(
        "front_matter",
        [
            '"title": Quoted',
            "'title': Quoted",
            "page title: Spaced\ntitle: Quoted",
            "title: Quoted",
        ],
    )
    def test_quoted_and_spaced_keys_are_yaml(self, front_matter: str) -> None:
        document = parse(f"---\n{front_matter}\n---\n\n## Body\n\ntext\n")
        assert paths(document) == [PREAMBLE_TITLE, "Body"]
        assert document.title in {"Quoted", "Body"}  # never the raw YAML as a setext heading
        assert not any(
            section.heading_level == 2 and "title" in section.heading_title.lower()
            for section in document.sections
        )


def test_heading_shares_part_one_with_an_over_long_line() -> None:
    text = "## Release Notes\n\n" + "word " * 1500 + "\n"
    document = parse(text)
    first = document.sections[0]
    assert first.heading_path == "Release Notes (Part 1)"
    assert first.content.startswith("## Release Notes\n\nword word")
    assert len(first.content) > 1000
    assert all(len(s.content) <= DEFAULT_MAX_SECTION_CHARS for s in document.sections)
    assert join_parts(document.sections) == text.rstrip("\n")  # verbatim, trailing space kept


class TestRepairCostIsBounded:
    @staticmethod
    def style_guide(rules: int, language: str) -> str:
        rule = (
            "## Rule {n}\n\nProse line.\n\n```{lang}\n\n## Example heading\n\nBody text.\n```\n\n"
        )
        body = "".join(rule.format(n=n, lang=language) for n in range(rules))
        return "# Style Guide\n\n" + body + "```\n"  # one stray, never-closed fence at the end

    @pytest.mark.parametrize("language", ["markdown", "bash"])
    def test_tokenisations_do_not_grow_with_the_number_of_fences(
        self, language: str, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        calls = 0
        real = MarkdownParser._tokenize

        def counting(self: MarkdownParser, source: str) -> list[object]:
            nonlocal calls
            calls += 1
            return real(self, source)  # type: ignore[return-value]

        monkeypatch.setattr(MarkdownParser, "_tokenize", counting)
        document = MarkdownParser().parse(self.style_guide(300, language))
        headings = [s.heading_path for s in document.sections]
        assert headings[:2] == ["Style Guide", "Style Guide > Rule 0"]
        assert "Style Guide > Rule 299" in headings  # nothing lost, nothing invented
        assert not any("Example heading" in heading for heading in headings)
        # section building tokenises each section once for its units; repair adds a constant
        assert calls <= len(document.sections) + 40  # a literal: must not track the constant


class TestUnitsInsideContainers:
    def test_code_inside_a_blockquote_is_a_unit_and_the_section_is_searchable(
        self, db: Database, fake_embedder: FakeEmbedder, tmp_path: Path
    ) -> None:
        text = (
            "# Runbook\n\n## Rollback A Release\n\n"
            "> ```bash\n> orbitctl rollback frobnicate\n> ```\n\n"
            "## Release Notes\n\nNotes that mention frobnicate and rollback in passing.\n"
        )
        section = next(s for s in parse(text).sections if s.heading_title == "Rollback A Release")
        assert section.units == ("orbitctl rollback frobnicate",)
        root = tmp_path / "docs"
        root.mkdir()
        (root / "runbook.md").write_text(text)
        Indexer(db, fake_embedder).index_directory(root)
        searcher = HybridSearcher(db, fake_embedder)
        try:
            found = [r.heading_title for r in searcher.search("frobnicate rollback")]
        finally:
            searcher.close()
        assert "Rollback A Release" in found

    def test_each_quoted_paragraph_is_its_own_unit(self) -> None:
        units = parse("# T\n\n> first quoted para\n>\n> second quoted para\n").sections[0].units
        assert units == ("first quoted para", "second quoted para")

    def test_indented_code_and_html_inside_containers(self) -> None:
        text = "# T\n\n>     indented code\n\n- item\n\n  <div>html in item</div>\n"
        assert parse(text).sections[0].units == ("indented code", "item html in item")

    def test_br_separates_words_in_table_cells_and_headings(self) -> None:
        text = "# First<br>Second\n\n| Flag | Desc |\n| --- | --- |\n| `-a` | one<br/>two |\n"
        section = parse(text).sections[0]
        assert section.heading_title == "First Second"
        assert section.units == ("Flag: -a; Desc: one two",)


def test_every_row_of_a_split_table_becomes_a_unit() -> None:
    rows = "\n".join(
        f"| `--option-{n:03}` | A reasonably long description of option number {n} | `{n}` |"
        for n in range(60)
    )
    text = f"## All Options\n\n| Flag | Description | Default |\n| --- | --- | --- |\n{rows}\n"
    parts = parse(text).sections
    assert len(parts) >= 2
    units = [unit for part in parts for unit in part.units]
    assert len(units) == 60
    assert units[-1].startswith("Flag: --option-059; Description: A reasonably long")
    assert all(len(part.units) > 1 for part in parts)  # no part collapsed into one paragraph
    assert join_parts(parts) == text.rstrip("\n")  # stored content is still verbatim
    assert "| Flag |" not in parts[1].content  # the header is restored for units only


class TestFrontMatterAdmonitions:
    def test_admonition_line_between_rules_is_a_heading_not_metadata(self) -> None:
        document = parse("---\nNote: this is prose, not YAML\n---\n\n# Heading\n\nBody\n")
        assert "Note: this is prose, not YAML" in paths(document)
        assert document.title == "Heading"

    def test_single_real_key_is_still_front_matter(self) -> None:
        document = parse("---\ntitle: Real\n---\n\n## Body\n\ntext\n")
        assert (document.title, paths(document)) == ("Real", [PREAMBLE_TITLE, "Body"])
